language: node_js

cache:
  yarn: true
  directories:
    - "node_modules"

before_script:
  - npm install -g yarn
  - yarn install

script:
  - npm run lint
  - npm run build
  - npm run security-checker
  - npm run test